version: '3.8'

services:
  backend:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_NAME=grading_system
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - SESSION_SECRET=your-super-secret-session-key-change-in-production
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - grading-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=grading_system
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - grading-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  grading-network:
    driver: bridge
